### PR TITLE
Include flood indication

### LINKED ISSUE #98: color ring for flood
test with just 95% only to see if it visually works

### PR DESCRIPTION
**Pull request by lindsaycarr**
Fixes #98. We did not add any indication for peak low flows. There are some sites that had stage data, but no daily flows (they are shown as "No data"), and some that had daily flows but not daily stage. Also, 3 gages in FL had a flood stage of 2 but their minimum flow for the entire year were all above 10 (they were perpetually above flood stage), so these are ignored for showing floods.

70% of the data are missing daily stage for WY18 (2,085,614 do not have daily stage out of 2,973,265 total records)
52% are missing a flood stage (1,557,154 do not have flood stage out of 2,973,265 total records)
65% have a flood stage, but no daily stage (918,606 do not have daily stage out of 1,416,111 observations with flood stage)

image

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Hmm, so maybe 20-30% of sites have the potential to show a flood symbol?

**Comment by lindsaycarr** [comment]
Looks like that number is actually 17% if you look at which observations have both stage and a flood stage
```
x_allobs <- readRDS("2_process/out/dv_stat_styles.rds")
x_canflood <- dplyr::filter(x_allobs, !is.na(dv_stage) & !is.na(flood_stage))
nrow(x_canflood) / nrow(x_allobs)
```

**Comment by lindsaycarr** [comment]
I'm really not sure why there are so many that don't have stage available. I question that number just because don't we use stage to calculate the flow at almost every gage?

**Comment by aappling-usgs** [comment]
Interesting thought on instantaneous vs daily, I think worth investigating if you have the time.

Seems like this movie could help Chad and others advocate for the development of flood stages and the dissemination of stage data more consistently nationally - it would clearly add value to information products like this one. I wonder if that's something that GWSIP is interested in promoting; if so, we could help them further by providing a Venn diagram or other graphic to illustrate the results you just shared here.

**Comment by lindsaycarr** [comment]
Conclusion: all sites have inst stage, but not all in NWISWeb. I started a branch that would allow us to calculate daily stage for those sites that have flood stage and discharge but no daily stage (see ). PR for that coming soon. So, it will add some more stage data and potential flooding points if they have instantaneous stage in NWISWeb.

**Pull request merged**
