### PR TITLE
Vertical legend

### LINKED ISSUE #56: Flip the legend to be vertical?
This would make it possible to place to the left of the map and use up that empty space.

### PR DESCRIPTION
**Pull request by lindsaycarr**
Trying vertical legend out for size. Fixes #56.

image

### CODE REVIEW

**Comment by lindsaycarr** [comment]
With updated design (changed legend text + legend above datewheel):

image

**Comment by aappling-usgs** [comment]
Late to the style conversation, but I would like to put in my vote for the labeling in the first image in this thread - I didn't find that one confusing, and I don't love how the line breaks before "flows" turned out (second image above - I find that _more_ confusing). If we're committed to the line breaks anyway, I like the arrows prototyped on the left in this image (from Slack): image

**Comment by lindsaycarr** [comment]
How about this? Should I move "Higher" and "Lower" to the edge? Just want to be cautious of Jordan's feedback about them looking like they apply to just that final value.

image

**Comment by aappling-usgs** [comment]
What about positioning the labels so they clearly don't match any one dot?
gage-legend

**Comment by lindsaycarr** [comment]
With most recent code changes:

image

**Comment by aappling-usgs** [comment]
:+1:

**Pull request merged**
